export const Needs = {
  Clarity: [
    'Understanding',
    'Stimulation',
    'Completion',
    'Comprehension',
    'Information',
    'Awareness',
    'Reflection',
    'Discrimination',
  ],

  Reassurance: [
    'Acceptance',
    'Appreciation',
    'Love',
    'Support',
    'Trust',
    'Respect',
    'Emotional Safety',
    'Consideration',
  ],

  Freedom: [
    'Autonomy',
    'Freedom',
    'Independence',
    'Choice',
    'Inviduality',
    'Self-Empowerment',
    'Solitude',
    'Play',
    'Humor',
  ],

  Expression: [
    'Creativity',
    'Growth',
    'Learning Mastery',
    'Meaning',
    'Teaching',
    'Grief',
    'Excitement',
    'Passion',
  ],

  integrity: [
    'Self–Worth',
    'Authenticity',
    'Confidence',
    'Purpose',
    'Vision / Dreams',
    'Honesty',
    'Humility',
    'Justice',
  ],

  Care: [
    'Empathy',
    'Contribution',
    'Community',
    'Emotional safety',
    'Understanding',
    'Disclosure',
    'Compassion',
    'Respect',
  ],

  Connection: [
    'Touch',
    'Physical Affection',
    'Warmth',
    'Tenderness',
    'Caring',
    'Bonding',
    'Comfort',
    'Intimacy',
    'Love',
    'Sincerity',
  ],

  Ease: [
    'Beauty / Aesthetic',
    'Harmony / Peace',
    'Order',
    'Inspiration',
    'Ease',
    'Awareness',
    'Spirituality',
    'Truth',
    'Relief',
    'Release',
  ],

  Physical: [
    'Health',
    'Air',
    'Food',
    'Sleep',
    'Water',
    'Shelter',
    'Safety',
    'Rest',
    'Movement',
    'Sex',
  ],
};

export const Feelings = {
  Glad: [
    'Confident',
    'Delighted',
    'Encouraged',
    'Excited',
    'Grateful',
    'Happy',
    'Hopeful',
    'Inspired',
    'Optimistic',
    'Proud',
    'Relieved',
    'Satisfied',
    'Touched',
  ],

  Peaceful: [
    'Absorbed',
    'Amazed',
    'Blissful',
    'Calm',
    'Comfortable',
    'Confident',
    'Content',
    'Fulfilled',
    'Loving',
    'Relaxed',
    'Satisfied',
    'Secure',
    'Serene',
  ],

  Playful: [
    'Adventurous',
    'Alive',
    'Curious',
    'Eager',
    'Energetic',
    'Exhilarated',
    'Exuberant',
    'Fascinated',
    'Free',
    'Intrigued',
    'Invigorated',
    'Refreshed',
    'Stimulated',
  ],

  Sad: [
    'Anguished',
    'Ashamed',
    'Brokenhearted',
    'Depressed',
    'Disappointed',
    'Discouraged',
    'Down',
    'Helpless',
    'Lonely',
    'Miserable',
    'Troubled',
  ],

  Loving: [
    'Affectionate',
    'Amorous',
    'Appreciative',
    'Aroused',
    'Compassionate',
    'Friendly',
    'Grateful',
    'Moved',
    'Nurtured/Nurturing',
    'Sensitive',
    'Tender',
    'Trusting',
    'Warm',
  ],

  Tense: [
    'Anxious',
    'Nervous',
    'Overwhelmed',
    'Panicky',
    'Shaky',
    'Shocked',
    'Skeptical',
    'Surprised',
    'Tense',
    'Terrified',
    'Worried',
  ],

  Mad: [
    'Angry',
    'Annoyed',
    'Bitter',
    'Disgusted',
    'Furious',
    'Impatient',
    'Irritated',
    'Jealous',
    'Keyed Up',
    'Pessimistic',
    'Resentful',
    'Restless',
  ],

  Tired: [
    'Beat',
    'Exhausted',
    'Fatigued',
    'Fidgety',
    'Heavy',
    'Helpless',
    'Indifferent',
    'Lethargic',
    'Listless',
    'Overwhelmed',
    'Sleepy',
    'Weary',
  ],

  Lost: [
    'Bewildered',
    'Confused',
    'Embarrassed',
    'Frustrated',
    'Hesitant',
    'Hurt',
    'Puzzled',
    'Reluctant',
    'Torn',
    'Troubled',
    'Uncomfortable',
    'Uneasy',
  ],
};

export const Topics = {
  Glad: [
    'Confident',
    'Delighted',
    'Encouraged',
    'Excited',
    'Grateful',
    'Happy',
    'Hopeful',
    'Inspired',
    'Optimistic',
    'Proud',
    'Relieved',
    'Satisfied',
    'Touched',
  ],

  Peaceful: [
    'Absorbed',
    'Amazed',
    'Blissful',
    'Calm',
    'Comfortable',
    'Confident',
    'Content',
    'Fulfilled',
    'Loving',
    'Relaxed',
    'Satisfied',
    'Secure',
    'Serene',
  ],

  Playful: [
    'Adventurous',
    'Alive',
    'Curious',
    'Eager',
    'Energetic',
    'Exhilarated',
    'Exuberant',
    'Fascinated',
    'Free',
    'Intrigued',
    'Invigorated',
    'Refreshed',
    'Stimulated',
  ],

  Sad: [
    'Anguished',
    'Ashamed',
    'Brokenhearted',
    'Depressed',
    'Disappointed',
    'Discouraged',
    'Down',
    'Helpless',
    'Lonely',
    'Miserable',
    'Troubled',
  ],

  Loving: [
    'Affectionate',
    'Amorous',
    'Appreciative',
    'Aroused',
    'Compassionate',
    'Friendly',
    'Grateful',
    'Moved',
    'Nurtured/Nurturing',
    'Sensitive',
    'Tender',
    'Trusting',
    'Warm',
  ],

  Tense: [
    'Anxious',
    'Nervous',
    'Overwhelmed',
    'Panicky',
    'Shaky',
    'Shocked',
    'Skeptical',
    'Surprised',
    'Tense',
    'Terrified',
    'Worried',
  ],

  Mad: [
    'Angry',
    'Annoyed',
    'Bitter',
    'Disgusted',
    'Furious',
    'Impatient',
    'Irritated',
    'Jealous',
    'Keyed Up',
    'Pessimistic',
    'Resentful',
    'Restless',
  ],

  Tired: [
    'Beat',
    'Exhausted',
    'Fatigued',
    'Fidgety',
    'Heavy',
    'Helpless',
    'Indifferent',
    'Lethargic',
    'Listless',
    'Overwhelmed',
    'Sleepy',
    'Weary',
  ],

  Lost: [
    'Bewildered',
    'Confused',
    'Embarrassed',
    'Frustrated',
    'Hesitant',
    'Hurt',
    'Puzzled',
    'Reluctant',
    'Torn',
    'Troubled',
    'Uncomfortable',
    'Uneasy',
  ],
};

export const Thoughts = {
  Glad: [
    'Confident',
    'Delighted',
    'Encouraged',
    'Excited',
    'Grateful',
    'Happy',
    'Hopeful',
    'Inspired',
    'Optimistic',
    'Proud',
    'Relieved',
    'Satisfied',
    'Touched',
  ],

  Peaceful: [
    'Absorbed',
    'Amazed',
    'Blissful',
    'Calm',
    'Comfortable',
    'Confident',
    'Content',
    'Fulfilled',
    'Loving',
    'Relaxed',
    'Satisfied',
    'Secure',
    'Serene',
  ],

  Playful: [
    'Adventurous',
    'Alive',
    'Curious',
    'Eager',
    'Energetic',
    'Exhilarated',
    'Exuberant',
    'Fascinated',
    'Free',
    'Intrigued',
    'Invigorated',
    'Refreshed',
    'Stimulated',
  ],

  Sad: [
    'Anguished',
    'Ashamed',
    'Brokenhearted',
    'Depressed',
    'Disappointed',
    'Discouraged',
    'Down',
    'Helpless',
    'Lonely',
    'Miserable',
    'Troubled',
  ],

  Loving: [
    'Affectionate',
    'Amorous',
    'Appreciative',
    'Aroused',
    'Compassionate',
    'Friendly',
    'Grateful',
    'Moved',
    'Nurtured/Nurturing',
    'Sensitive',
    'Tender',
    'Trusting',
    'Warm',
  ],

  Tense: [
    'Anxious',
    'Nervous',
    'Overwhelmed',
    'Panicky',
    'Shaky',
    'Shocked',
    'Skeptical',
    'Surprised',
    'Tense',
    'Terrified',
    'Worried',
  ],

  Mad: [
    'Angry',
    'Annoyed',
    'Bitter',
    'Disgusted',
    'Furious',
    'Impatient',
    'Irritated',
    'Jealous',
    'Keyed Up',
    'Pessimistic',
    'Resentful',
    'Restless',
  ],

  Tired: [
    'Beat',
    'Exhausted',
    'Fatigued',
    'Fidgety',
    'Heavy',
    'Helpless',
    'Indifferent',
    'Lethargic',
    'Listless',
    'Overwhelmed',
    'Sleepy',
    'Weary',
  ],

  Lost: [
    'Bewildered',
    'Confused',
    'Embarrassed',
    'Frustrated',
    'Hesitant',
    'Hurt',
    'Puzzled',
    'Reluctant',
    'Torn',
    'Troubled',
    'Uncomfortable',
    'Uneasy',
  ],
};

export const Actions = {
  Glad: [
    'Confident',
    'Delighted',
    'Encouraged',
    'Excited',
    'Grateful',
    'Happy',
    'Hopeful',
    'Inspired',
    'Optimistic',
    'Proud',
    'Relieved',
    'Satisfied',
    'Touched',
  ],

  Peaceful: [
    'Absorbed',
    'Amazed',
    'Blissful',
    'Calm',
    'Comfortable',
    'Confident',
    'Content',
    'Fulfilled',
    'Loving',
    'Relaxed',
    'Satisfied',
    'Secure',
    'Serene',
  ],

  Playful: [
    'Adventurous',
    'Alive',
    'Curious',
    'Eager',
    'Energetic',
    'Exhilarated',
    'Exuberant',
    'Fascinated',
    'Free',
    'Intrigued',
    'Invigorated',
    'Refreshed',
    'Stimulated',
  ],

  Sad: [
    'Anguished',
    'Ashamed',
    'Brokenhearted',
    'Depressed',
    'Disappointed',
    'Discouraged',
    'Down',
    'Helpless',
    'Lonely',
    'Miserable',
    'Troubled',
  ],

  Loving: [
    'Affectionate',
    'Amorous',
    'Appreciative',
    'Aroused',
    'Compassionate',
    'Friendly',
    'Grateful',
    'Moved',
    'Nurtured/Nurturing',
    'Sensitive',
    'Tender',
    'Trusting',
    'Warm',
  ],

  Tense: [
    'Anxious',
    'Nervous',
    'Overwhelmed',
    'Panicky',
    'Shaky',
    'Shocked',
    'Skeptical',
    'Surprised',
    'Tense',
    'Terrified',
    'Worried',
  ],

  Mad: [
    'Angry',
    'Annoyed',
    'Bitter',
    'Disgusted',
    'Furious',
    'Impatient',
    'Irritated',
    'Jealous',
    'Keyed Up',
    'Pessimistic',
    'Resentful',
    'Restless',
  ],

  Tired: [
    'Beat',
    'Exhausted',
    'Fatigued',
    'Fidgety',
    'Heavy',
    'Helpless',
    'Indifferent',
    'Lethargic',
    'Listless',
    'Overwhelmed',
    'Sleepy',
    'Weary',
  ],

  Lost: [
    'Bewildered',
    'Confused',
    'Embarrassed',
    'Frustrated',
    'Hesitant',
    'Hurt',
    'Puzzled',
    'Reluctant',
    'Torn',
    'Troubled',
    'Uncomfortable',
    'Uneasy',
  ],
};

export const Facts = {
  Glad: [
    'Confident',
    'Delighted',
    'Encouraged',
    'Excited',
    'Grateful',
    'Happy',
    'Hopeful',
    'Inspired',
    'Optimistic',
    'Proud',
    'Relieved',
    'Satisfied',
    'Touched',
  ],

  Peaceful: [
    'Absorbed',
    'Amazed',
    'Blissful',
    'Calm',
    'Comfortable',
    'Confident',
    'Content',
    'Fulfilled',
    'Loving',
    'Relaxed',
    'Satisfied',
    'Secure',
    'Serene',
  ],

  Playful: [
    'Adventurous',
    'Alive',
    'Curious',
    'Eager',
    'Energetic',
    'Exhilarated',
    'Exuberant',
    'Fascinated',
    'Free',
    'Intrigued',
    'Invigorated',
    'Refreshed',
    'Stimulated',
  ],

  Sad: [
    'Anguished',
    'Ashamed',
    'Brokenhearted',
    'Depressed',
    'Disappointed',
    'Discouraged',
    'Down',
    'Helpless',
    'Lonely',
    'Miserable',
    'Troubled',
  ],

  Loving: [
    'Affectionate',
    'Amorous',
    'Appreciative',
    'Aroused',
    'Compassionate',
    'Friendly',
    'Grateful',
    'Moved',
    'Nurtured/Nurturing',
    'Sensitive',
    'Tender',
    'Trusting',
    'Warm',
  ],

  Tense: [
    'Anxious',
    'Nervous',
    'Overwhelmed',
    'Panicky',
    'Shaky',
    'Shocked',
    'Skeptical',
    'Surprised',
    'Tense',
    'Terrified',
    'Worried',
  ],

  Mad: [
    'Angry',
    'Annoyed',
    'Bitter',
    'Disgusted',
    'Furious',
    'Impatient',
    'Irritated',
    'Jealous',
    'Keyed Up',
    'Pessimistic',
    'Resentful',
    'Restless',
  ],

  Tired: [
    'Beat',
    'Exhausted',
    'Fatigued',
    'Fidgety',
    'Heavy',
    'Helpless',
    'Indifferent',
    'Lethargic',
    'Listless',
    'Overwhelmed',
    'Sleepy',
    'Weary',
  ],

  Lost: [
    'Bewildered',
    'Confused',
    'Embarrassed',
    'Frustrated',
    'Hesitant',
    'Hurt',
    'Puzzled',
    'Reluctant',
    'Torn',
    'Troubled',
    'Uncomfortable',
    'Uneasy',
  ],
};

export const Merits = {
  Glad: [
    'Confident',
    'Delighted',
    'Encouraged',
    'Excited',
    'Grateful',
    'Happy',
    'Hopeful',
    'Inspired',
    'Optimistic',
    'Proud',
    'Relieved',
    'Satisfied',
    'Touched',
  ],

  Peaceful: [
    'Absorbed',
    'Amazed',
    'Blissful',
    'Calm',
    'Comfortable',
    'Confident',
    'Content',
    'Fulfilled',
    'Loving',
    'Relaxed',
    'Satisfied',
    'Secure',
    'Serene',
  ],

  Playful: [
    'Adventurous',
    'Alive',
    'Curious',
    'Eager',
    'Energetic',
    'Exhilarated',
    'Exuberant',
    'Fascinated',
    'Free',
    'Intrigued',
    'Invigorated',
    'Refreshed',
    'Stimulated',
  ],

  Sad: [
    'Anguished',
    'Ashamed',
    'Brokenhearted',
    'Depressed',
    'Disappointed',
    'Discouraged',
    'Down',
    'Helpless',
    'Lonely',
    'Miserable',
    'Troubled',
  ],

  Loving: [
    'Affectionate',
    'Amorous',
    'Appreciative',
    'Aroused',
    'Compassionate',
    'Friendly',
    'Grateful',
    'Moved',
    'Nurtured/Nurturing',
    'Sensitive',
    'Tender',
    'Trusting',
    'Warm',
  ],

  Tense: [
    'Anxious',
    'Nervous',
    'Overwhelmed',
    'Panicky',
    'Shaky',
    'Shocked',
    'Skeptical',
    'Surprised',
    'Tense',
    'Terrified',
    'Worried',
  ],

  Mad: [
    'Angry',
    'Annoyed',
    'Bitter',
    'Disgusted',
    'Furious',
    'Impatient',
    'Irritated',
    'Jealous',
    'Keyed Up',
    'Pessimistic',
    'Resentful',
    'Restless',
  ],

  Tired: [
    'Beat',
    'Exhausted',
    'Fatigued',
    'Fidgety',
    'Heavy',
    'Helpless',
    'Indifferent',
    'Lethargic',
    'Listless',
    'Overwhelmed',
    'Sleepy',
    'Weary',
  ],

  Lost: [
    'Bewildered',
    'Confused',
    'Embarrassed',
    'Frustrated',
    'Hesitant',
    'Hurt',
    'Puzzled',
    'Reluctant',
    'Torn',
    'Troubled',
    'Uncomfortable',
    'Uneasy',
  ],
};

export const People = {
  Glad: [
    'Confident',
    'Delighted',
    'Encouraged',
    'Excited',
    'Grateful',
    'Happy',
    'Hopeful',
    'Inspired',
    'Optimistic',
    'Proud',
    'Relieved',
    'Satisfied',
    'Touched',
  ],

  Peaceful: [
    'Absorbed',
    'Amazed',
    'Blissful',
    'Calm',
    'Comfortable',
    'Confident',
    'Content',
    'Fulfilled',
    'Loving',
    'Relaxed',
    'Satisfied',
    'Secure',
    'Serene',
  ],

  Playful: [
    'Adventurous',
    'Alive',
    'Curious',
    'Eager',
    'Energetic',
    'Exhilarated',
    'Exuberant',
    'Fascinated',
    'Free',
    'Intrigued',
    'Invigorated',
    'Refreshed',
    'Stimulated',
  ],

  Sad: [
    'Anguished',
    'Ashamed',
    'Brokenhearted',
    'Depressed',
    'Disappointed',
    'Discouraged',
    'Down',
    'Helpless',
    'Lonely',
    'Miserable',
    'Troubled',
  ],

  Loving: [
    'Affectionate',
    'Amorous',
    'Appreciative',
    'Aroused',
    'Compassionate',
    'Friendly',
    'Grateful',
    'Moved',
    'Nurtured/Nurturing',
    'Sensitive',
    'Tender',
    'Trusting',
    'Warm',
  ],

  Tense: [
    'Anxious',
    'Nervous',
    'Overwhelmed',
    'Panicky',
    'Shaky',
    'Shocked',
    'Skeptical',
    'Surprised',
    'Tense',
    'Terrified',
    'Worried',
  ],

  Mad: [
    'Angry',
    'Annoyed',
    'Bitter',
    'Disgusted',
    'Furious',
    'Impatient',
    'Irritated',
    'Jealous',
    'Keyed Up',
    'Pessimistic',
    'Resentful',
    'Restless',
  ],

  Tired: [
    'Beat',
    'Exhausted',
    'Fatigued',
    'Fidgety',
    'Heavy',
    'Helpless',
    'Indifferent',
    'Lethargic',
    'Listless',
    'Overwhelmed',
    'Sleepy',
    'Weary',
  ],

  Lost: [
    'Bewildered',
    'Confused',
    'Embarrassed',
    'Frustrated',
    'Hesitant',
    'Hurt',
    'Puzzled',
    'Reluctant',
    'Torn',
    'Troubled',
    'Uncomfortable',
    'Uneasy',
  ],
};
