export const Needs = {
  Clarity: [
    'Understanding',
    'Stimulation',
    'Completion',
    'Comprehension',
    'Information',
    'Awareness',
    'Reflection',
    'Discrimination',
  ],

  Reassurance: [
    'Acceptance',
    'Appreciation',
    'Love',
    'Support',
    'Trust',
    'Respect',
    'Emotional Safety',
    'Consideration',
  ],

  Freedom: [
    'Autonomy',
    'Freedom',
    'Independence',
    'Choice',
    'Inviduality',
    'Self-Empowerment',
    'Solitude',
    'Play',
    'Humor',
  ],

  Expression: [
    'Creativity',
    'Growth',
    'Learning Mastery',
    'Meaning',
    'Teaching',
    'Grief',
    'Excitement',
    'Passion',
  ],

  integrity: [
    'Self–Worth',
    'Authenticity',
    'Confidence',
    'Purpose',
    'Vision / Dreams',
    'Honesty',
    'Humility',
    'Justice',
  ],

  Care: [
    'Empathy',
    'Contribution',
    'Community',
    'Emotional safety',
    'Understanding',
    'Disclosure',
    'Compassion',
    'Respect',
  ],

  Connection: [
    'Touch',
    'Physical Affection',
    'Warmth',
    'Tenderness',
    'Caring',
    'Bonding',
    'Comfort',
    'Intimacy',
    'Love',
    'Sincerity',
  ],

  Ease: [
    'Beauty / Aesthetic',
    'Harmony / Peace',
    'Order',
    'Inspiration',
    'Ease',
    'Awareness',
    'Spirituality',
    'Truth',
    'Relief',
    'Release',
  ],

  Physical: [
    'Health',
    'Air',
    'Food',
    'Sleep',
    'Water',
    'Shelter',
    'Safety',
    'Rest',
    'Movement',
    'Sex',
  ],
};
